### ISSUE TITLE
Authentication i produktionsmiljø

### ISSUE THREAD

**Issue by CSL-randers** [Randers-Kommune-Digitalisering/auto-bankposteringer-nordea-kmdopus#3]
Af en eller anden grund virker nøglerne fra Nordea ikke i samme workflow hvor testmiljøet virker fint.
Det er muligt at produktionsmiljøet eksisterer i nyere versioner af de endpoints der bruges i testmiljøet, da visse http requests smider en 405 error.

```[tasklist]
### Tasks
- [x] Tjek om eIDAS nøglens format skal laves om
- [x] Tjek om Codespaces secrets er rigtige
- [x] Skriv evt. til Nordeas udviklere eller Ole Torp
```

**Comment by CSL-randers** [comment]
Der skulle bruges en anden version og det viste sig at Jan skal forny auth hver gang der kaldes på auth endpointet.
